name: Poetry Test Suite
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8"]
    runs-on: ${{ matrix.os }}
    name: Python${{ matrix.python-version }} Test
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

      - name: Install Python dependencies
        run: ~/.poetry/bin/poetry install

      - name: Test
        run: ~/.poetry/bin/poetry run pytest
